# Generated by Django 3.1.4 on 2020-12-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_caracteristicas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristicas',
            options={'verbose_name': 'Caracteristica', 'verbose_name_plural': 'Caracteristicas'},
        ),
    ]
