# Generated by Django 3.1.4 on 2020-12-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201229_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Laptop'), ('lni-users', 'Usuários'), ('lni-layers', 'Foguete'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], max_length=16, verbose_name='Icone'),
        ),
    ]
